[package]
name = "emu_cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emu_utils = { path = "../emu_utils" }
emu_macros = { path = "../emu_macros" }